name: ci
on:
  - push
jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node:
          - '12.x'
          - '14.x'
          - 'lts/*'
        band:
          - 'webpack4'
          - 'webpack5'
    steps:
        - name: Use OS ${{ matrix.os }}
          uses: actions/checkout@v2
        - name: Use Node@${{ matrix.node }}
          uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.node }}
            cache: 'yarn'
        - name: Install Dependencies
          run: yarn install
        - name: Unit test
          run: yarn test:unit
        - name: End-to-End test ${{ matrix.band }}
          if: ${{ !(matrix.node == 'lts/*' && matrix.band == 'webpack4') }}
          run: yarn test:e2e
          env:
            ONLY: '${{ matrix.band }}*'
